<a href="https://colab.research.google.com/github/lavanyayada112/Netflix-Data-Analysis/blob/main/netflix_data_analysis_project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Import Libraries and data

In [ ]:

import numpy as np #Linear algebra operations
import pandas as pd # used for data preparation
import plotly.express as px #used for data visualization
from textblob import TextBlob #used for sentiment analysis

df = pd.read_csv('/content/netflix_titles_nov_2019.csv')

#Checking number of rows and column in data

In [ ]:
df.shape

(5837, 12)

#Checking content available in dataset

In [ ]:
df.head()

,show_id,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,type
0,81193313,Chocolate,NaN,"Ha Ji-won, Yoon Kye-sang, Jang Seung-jo, Kang ...",South Korea,"November 30, 2019",2019,TV-14,1 Season,"International TV Shows, Korean TV Shows, Roman...",Brought together by meaningful meals in the pa...,TV Show
1,81197050,Guatemala: Heart of the Mayan World,"Luis Ara, Ignacio Jaunsolo",Christian Morales,NaN,"November 30, 2019",2019,TV-G,67 min,"Documentaries, International Movies","From Sierra de las Minas to Esquipulas, explor...",Movie
2,81213894,The Zoya Factor,Abhishek Sharma,"Sonam Kapoor, Dulquer Salmaan, Sanjay Kapoor, ...",India,"November 30, 2019",2019,TV-14,135 min,"Comedies, Dramas, International Movies",A goofy copywriter unwittingly convinces the I...,Movie
3,81082007,Atlantics,Mati Diop,"Mama Sane, Amadou Mbow, Ibrahima Traore, Nicol...","France, Senegal, Belgium","November 29, 2019",2019,TV-14,106 min,"Dramas, Independent Movies, International Movies","Arranged to marry a rich man, young Ada is cru...",Movie
4,80213643,Chip and Potato,NaN,"Abigail Oliver, Andrea Libman, Briana Buckmast...","Canada, United Kingdom",NaN,2019,TV-Y,2 Seasons,Kids' TV,"Lovable pug Chip starts kindergarten, makes ne...",TV Show

#How to check columns name of dataset

In [ ]:
df.columns

Index(['show_id', 'title', 'director', 'cast', 'country', 'date_added',
       'release_year', 'rating', 'duration', 'listed_in', 'description',
       'type'],
      dtype='object')

#Taking the count of rating

In [ ]:
x = df.groupby(['rating']).size().reset_index(name='counts')
print(x)

      rating  counts
0          G      32
1      NC-17       2
2         NR     218
3         PG     160
4      PG-13     227
5          R     439
6      TV-14    1593
7       TV-G     147
8      TV-MA    1937
9      TV-PG     678
10      TV-Y     139
11     TV-Y7     156
12  TV-Y7-FV      92
13        UR       7

#Creating the piechart on content rating

In [ ]:
pieChart = px.pie(x, values='counts', names='rating', title='Distribution of content Ratings on Netflix')
pieChart.show()

#Analyzing the top 5 directors

In [ ]:
df['director'] = df['director'].fillna('Director not  Specified')
df.head()

,show_id,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,type
0,81193313,Chocolate,Director not Specified,"Ha Ji-won, Yoon Kye-sang, Jang Seung-jo, Kang ...",South Korea,"November 30, 2019",2019,TV-14,1 Season,"International TV Shows, Korean TV Shows, Roman...",Brought together by meaningful meals in the pa...,TV Show
1,81197050,Guatemala: Heart of the Mayan World,"Luis Ara, Ignacio Jaunsolo",Christian Morales,NaN,"November 30, 2019",2019,TV-G,67 min,"Documentaries, International Movies","From Sierra de las Minas to Esquipulas, explor...",Movie
2,81213894,The Zoya Factor,Abhishek Sharma,"Sonam Kapoor, Dulquer Salmaan, Sanjay Kapoor, ...",India,"November 30, 2019",2019,TV-14,135 min,"Comedies, Dramas, International Movies",A goofy copywriter unwittingly convinces the I...,Movie
3,81082007,Atlantics,Mati Diop,"Mama Sane, Amadou Mbow, Ibrahima Traore, Nicol...","France, Senegal, Belgium","November 29, 2019",2019,TV-14,106 min,"Dramas, Independent Movies, International Movies","Arranged to marry a rich man, young Ada is cru...",Movie
4,80213643,Chip and Potato,Director not Specified,"Abigail Oliver, Andrea Libman, Briana Buckmast...","Canada, United Kingdom",NaN,2019,TV-Y,2 Seasons,Kids' TV,"Lovable pug Chip starts kindergarten, makes ne...",TV Show

In [ ]:
directors_list = pd.DataFrame()
print(directors_list)

Empty DataFrame
Columns: []
Index: []

In [ ]:
directors_list = df['director'].str.split(',', expand=True).stack()
print(directors_list)

0     0    Director not  Specified
1     0                   Luis Ara
      1           Ignacio Jaunsolo
2     0            Abhishek Sharma
3     0                  Mati Diop
                    ...
5832  0                 Jim Monaco
5833  0                  Joe Dante
5834  0               Ole Bornedal
5835  0    Director not  Specified
5836  0       Sorin Dan Mihalcescu
Length: 6398, dtype: object

In [ ]:
directors_list = directors_list.to_frame()
print(directors_list)

                              0
0    0  Director not  Specified
1    0                 Luis Ara
     1         Ignacio Jaunsolo
2    0          Abhishek Sharma
3    0                Mati Diop
...                         ...
5832 0               Jim Monaco
5833 0                Joe Dante
5834 0             Ole Bornedal
5835 0  Director not  Specified
5836 0     Sorin Dan Mihalcescu

[6398 rows x 1 columns]

In [ ]:
directors_list.columns = ['director']
print(directors_list)

                       director
0    0  Director not  Specified
1    0                 Luis Ara
     1         Ignacio Jaunsolo
2    0          Abhishek Sharma
3    0                Mati Diop
...                         ...
5832 0               Jim Monaco
5833 0                Joe Dante
5834 0             Ole Bornedal
5835 0  Director not  Specified
5836 0     Sorin Dan Mihalcescu

[6398 rows x 1 columns]

In [ ]:
directors = directors_list.groupby(['director']).size().reset_index(name=' Total counts')
print(directors)

                       director   Total counts
0                Aaron Moorhead              1
1                   Aaron Woolf              1
2      Abbas Alibhai Burmawalla              1
3           Abhinav Shiv Tiwari              1
4                  Adam Carolla              2
...                         ...            ...
3523                Çagan Irmak              1
3524           Ísold Uggadóttir              1
3525        Óskar Thór Axelsson              1
3526           Ömer Faruk Sorak              2
3527               Şenol Sönmez              2

[3528 rows x 2 columns]

In [ ]:
directors = directors[directors.director != 'Director not Specified']

In [ ]:
print(directors)

                       director   Total counts
0                Aaron Moorhead              1
1                   Aaron Woolf              1
2      Abbas Alibhai Burmawalla              1
3           Abhinav Shiv Tiwari              1
4                  Adam Carolla              2
...                         ...            ...
3523                Çagan Irmak              1
3524           Ísold Uggadóttir              1
3525        Óskar Thór Axelsson              1
3526           Ömer Faruk Sorak              2
3527               Şenol Sönmez              2

[3528 rows x 2 columns]

In [ ]:
directors = directors.sort_values(by=[' Total counts'],ascending = False)
print(directors)

                     director   Total counts
1248  Director not  Specified           1901
2816              Raúl Campos             18
189                 Jan Suter             18
2258             Marcus Raboy             14
1693                Jay Karas             14
...                       ...            ...
22               Allen Hughes              1
3511                 Zakariya              1
8                    Adam Nee              1
3513              Zeke Norton              1
3514              Zhang Yimou              1

[3528 rows x 2 columns]

In [ ]:
top5Directors = directors.head()
print(top5Directors)

                     director   Total counts
1248  Director not  Specified           1901
2816              Raúl Campos             18
189                 Jan Suter             18
2258             Marcus Raboy             14
1693                Jay Karas             14

In [ ]:
top5Directors = top5Directors.sort_values(by=[' Total counts'])
barChart = px.bar(top5Directors, x=' Total counts', y='director', title='Top 5 Directors on Netflix')
barChart.show()

#Analyzing the top 5 acting on Netflix

In [ ]:
df['cast'] = df['cast'].fillna('No cast Specified')
cast_df = pd.DataFrame()
cast_df = df['cast'].str.split(',', expand=True).stack()
cast_df = cast_df.to_frame()
cast_df.columns = ['Actor']
actors = cast_df.groupby(['Actor']).size().reset_index(name='Total Counts')
actors = actors[actors.Actor != 'No cast Specified']
actors = actors.sort_values(by=['Total Counts'], ascending=False)
top5Actors = actors.head()
top5Actors = top5Actors.sort_values(by=['Total Counts'])
barChart = px.bar(top5Actors, x='Total Counts', y='Actor', title='Top 5 Actors on Netflix')
barChart.show()

#Analyzing the content produced on netflix based on years

In [ ]:
df1 = df[['type','release_year']]
df1=df1.rename(columns = {"release_year":"Release Year", "type": "type"})
df2=df1.groupby(['Release Year','type']).size().reset_index(name='Total Content')

In [ ]:
print(df2)

     Release Year     type  Total Content
72           2000    Movie             19
73           2000  TV Show              3
74           2001    Movie             24
75           2001  TV Show              4
76           2002    Movie             23
77           2002  TV Show              3
78           2003    Movie             29
79           2003  TV Show              8
80           2004    Movie             33
81           2004  TV Show              8
82           2005    Movie             41
83           2005  TV Show             11
84           2006    Movie             48
85           2006  TV Show              9
86           2007    Movie             50
87           2007  TV Show             11
88           2008    Movie             82
89           2008  TV Show             20
90           2009    Movie             73
91           2009  TV Show             33
92           2010    Movie            100
93           2010  TV Show             37
94           2011    Movie             92
95           2011  TV Show             35
96           2012    Movie            119
97           2012  TV Show             55
98           2013    Movie            172
99           2013  TV Show             60
100          2014    Movie            206
101          2014  TV Show             75
102          2015    Movie            351
103          2015  TV Show            151
104          2016    Movie            584
105          2016  TV Show            234
106          2017    Movie            655
107          2017  TV Show            273
108          2018    Movie            630
109          2018  TV Show            410
110          2019    Movie            347
111          2019  TV Show            415
112          2020  TV Show              1

In [ ]:
df2 = df2[df2['Release Year']>=2000]
graph = px.line(df2, x="Release Year", y="Total Content", color="type", title="Trend of content produced on Netflix by Every Year")
graph.show()

#Sentiment Analysis of  netflix Content

In [ ]:
df3 = df[['release_year','description']]
df3 = df3.rename(columns={"release_year":"Release Year", "description":"Description"})

for index, row in df3.iterrows():
    d = row['Description']
    testimonial = TextBlob(d)
    p = testimonial.sentiment.polarity

    if p == 0:
        sent = 'Neutral'
    elif p > 0:
        sent = 'Positive'
    else:
        sent = 'Negative'

    df3.loc[index, 'Sentiment'] = sent

df3 = df3.groupby(['Release Year', 'Sentiment']).size().reset_index(name='Total Content')

df3 = df3[df3['Release Year'] >= 2005]

barGraph = px.bar(df3, x='Release Year', y='Total Content', color='Sentiment',
                  title='Sentiment Analysis of Netflix Content')
barGraph.show()